--------------------------------------------------------
-- Archivo creado  - viernes-diciembre-09-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AD_AFICION
--------------------------------------------------------

  CREATE TABLE "LALIGA"."AD_AFICION" 
   (	"AFICION_ID" NUMBER(20,0), 
	"NOMBRE_DE_GUERRA" VARCHAR2(20 BYTE), 
	"EQUIPO_ID" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "LALIGA"."AD_AFICION"."AFICION_ID" IS 'id de la aficion
¡¡¡ADVERTECIA!!!
SI BORRAS UNA AFICION, TAMBIEN BORRARAS SUS CANTICOS Y ALBOROTADORES';
   COMMENT ON COLUMN "LALIGA"."AD_AFICION"."NOMBRE_DE_GUERRA" IS 'nombre de la aficion';
   COMMENT ON COLUMN "LALIGA"."AD_AFICION"."EQUIPO_ID" IS 'equipo al que pertenece
¡¡¡ADVERTECIA!!!
SI BORRAS UN EQUIPO, SE BORRARA LA AFICION Y SUS DATOS RELACIONADOS';
--------------------------------------------------------
--  DDL for Table AD_ALBOROTADORES
--------------------------------------------------------

  CREATE TABLE "LALIGA"."AD_ALBOROTADORES" 
   (	"ALBOROTADOR_ID" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"DNI" VARCHAR2(10 BYTE), 
	"FECHA_NACIMIENTO" DATE, 
	"AFICION_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "LALIGA"."AD_ALBOROTADORES"."ALBOROTADOR_ID" IS 'ID DEL ALBOROTADOR';
   COMMENT ON COLUMN "LALIGA"."AD_ALBOROTADORES"."NOMBRE" IS 'NOMBRE';
   COMMENT ON COLUMN "LALIGA"."AD_ALBOROTADORES"."DNI" IS 'IDENTIFICACION';
   COMMENT ON COLUMN "LALIGA"."AD_ALBOROTADORES"."FECHA_NACIMIENTO" IS 'NACIMIENTO';
   COMMENT ON COLUMN "LALIGA"."AD_ALBOROTADORES"."AFICION_ID" IS 'AFICION A LA QUE PERTENECE
¡¡¡ADVERTECIA!!!
SI BORRAS LA AFICION CLAVE, TAMBIEN SE BORRAN LOS ALBOROTADORES';
--------------------------------------------------------
--  DDL for Table AD_CANTICO
--------------------------------------------------------

  CREATE TABLE "LALIGA"."AD_CANTICO" 
   (	"CANTICO_ID" NUMBER(10,0), 
	"TITULO" VARCHAR2(20 BYTE), 
	"AFICION_ID" NUMBER(10,0), 
	"LETRA" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "LALIGA"."AD_CANTICO"."CANTICO_ID" IS 'id del cantico';
   COMMENT ON COLUMN "LALIGA"."AD_CANTICO"."TITULO" IS 'Nombre del grito de guerra';
   COMMENT ON COLUMN "LALIGA"."AD_CANTICO"."AFICION_ID" IS 'ID DE LA AFICCION
¡¡¡ADVERTECIA!!!
SI BORRAS UNA AFICION SE BORRAN TODOS SUS CANTICOS';
--------------------------------------------------------
--  DDL for Table AD_EQUIPO
--------------------------------------------------------

  CREATE TABLE "LALIGA"."AD_EQUIPO" 
   (	"EQUIPO_ID" NUMBER(20,0), 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"ESTADIO_ID" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "LALIGA"."AD_EQUIPO"."EQUIPO_ID" IS 'ID DEL EQUIPO.
¡¡¡ADVERTECIA!!!
SI BORRAS UN EQUIPO, TAMBIEN BORRARAS LA AFICION';
   COMMENT ON COLUMN "LALIGA"."AD_EQUIPO"."NOMBRE" IS 'nombre del equipo';
   COMMENT ON COLUMN "LALIGA"."AD_EQUIPO"."ESTADIO_ID" IS 'ID DEL ESTADIO';
--------------------------------------------------------
--  DDL for Table AD_ESTADIOS
--------------------------------------------------------

  CREATE TABLE "LALIGA"."AD_ESTADIOS" 
   (	"ESTADIO_ID" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"EQUIPO_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "LALIGA"."AD_ESTADIOS"."ESTADIO_ID" IS 'ID de los estadios';
   COMMENT ON COLUMN "LALIGA"."AD_ESTADIOS"."NOMBRE" IS 'Nombre de los estadios';
--------------------------------------------------------
--  DDL for Table AD_JUGADORES
--------------------------------------------------------

  CREATE TABLE "LALIGA"."AD_JUGADORES" 
   (	"JUGADOR_ID" NUMBER(20,0), 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"EQUIPO_ID" NUMBER, 
	"SALARIO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "LALIGA"."AD_JUGADORES"."JUGADOR_ID" IS 'ID del Jugador';
   COMMENT ON COLUMN "LALIGA"."AD_JUGADORES"."NOMBRE" IS 'nombre del jugador';
   COMMENT ON COLUMN "LALIGA"."AD_JUGADORES"."SALARIO" IS 'SALARIO DE CADA JUGADOR
';
--------------------------------------------------------
--  DDL for Index AFICION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."AFICION_PK" ON "LALIGA"."AD_AFICION" ("AFICION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AD_ALBOROTADORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."AD_ALBOROTADORES_PK" ON "LALIGA"."AD_ALBOROTADORES" ("ALBOROTADOR_ID", "AFICION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AD_ALBOROTADORES_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."AD_ALBOROTADORES_PK1" ON "LALIGA"."AD_ALBOROTADORES" ("ALBOROTADOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CANTICO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."CANTICO_PK" ON "LALIGA"."AD_CANTICO" ("CANTICO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."EQUIPO_PK" ON "LALIGA"."AD_EQUIPO" ("EQUIPO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ESTADIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."ESTADIOS_PK" ON "LALIGA"."AD_ESTADIOS" ("ESTADIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index JUGADORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."JUGADORES_PK" ON "LALIGA"."AD_JUGADORES" ("JUGADOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AD_AFICION
--------------------------------------------------------

  ALTER TABLE "LALIGA"."AD_AFICION" MODIFY ("NOMBRE_DE_GUERRA" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."AD_AFICION" ADD CONSTRAINT "AFICION_PK" PRIMARY KEY ("AFICION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LALIGA"."AD_AFICION" MODIFY ("AFICION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AD_ALBOROTADORES
--------------------------------------------------------

  ALTER TABLE "LALIGA"."AD_ALBOROTADORES" ADD CONSTRAINT "AD_ALBOROTADORES_PK" PRIMARY KEY ("ALBOROTADOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LALIGA"."AD_ALBOROTADORES" MODIFY ("ALBOROTADOR_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."AD_ALBOROTADORES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."AD_ALBOROTADORES" MODIFY ("DNI" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."AD_ALBOROTADORES" MODIFY ("FECHA_NACIMIENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AD_CANTICO
--------------------------------------------------------

  ALTER TABLE "LALIGA"."AD_CANTICO" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."AD_CANTICO" MODIFY ("LETRA" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."AD_CANTICO" ADD CONSTRAINT "CANTICO_PK" PRIMARY KEY ("CANTICO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LALIGA"."AD_CANTICO" MODIFY ("CANTICO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AD_EQUIPO
--------------------------------------------------------

  ALTER TABLE "LALIGA"."AD_EQUIPO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."AD_EQUIPO" ADD CONSTRAINT "EQUIPO_PK" PRIMARY KEY ("EQUIPO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LALIGA"."AD_EQUIPO" MODIFY ("EQUIPO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AD_ESTADIOS
--------------------------------------------------------

  ALTER TABLE "LALIGA"."AD_ESTADIOS" ADD CONSTRAINT "ESTADIOS_PK" PRIMARY KEY ("ESTADIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LALIGA"."AD_ESTADIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."AD_ESTADIOS" MODIFY ("ESTADIO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AD_JUGADORES
--------------------------------------------------------

  ALTER TABLE "LALIGA"."AD_JUGADORES" MODIFY ("SALARIO" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."AD_JUGADORES" ADD CONSTRAINT "JUGADORES_PK" PRIMARY KEY ("JUGADOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LALIGA"."AD_JUGADORES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."AD_JUGADORES" MODIFY ("JUGADOR_ID" NOT NULL ENABLE);
